name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- ubuntu-latest
          #- macOS-latest
          - windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup julia  
      uses: julia-actions/setup-julia@v1
      with:
          version: '1.8'
          arch: 'x64'
    
    # Install required compilers 
    - name: Install GCC compilers macOS
      if: contains( matrix.os, 'macOS')
      run: |
          brew install gcc@12 
          sudo ln -s $(which gfortran-12) $(dirname $(which gfortran-12))/gfortran
    - name: Install compilers windows
      if: contains( matrix.os, 'windows')
      run: |
          choco install cmake
  
    # Compile source files (slightly different on windows vs. linux/mac because of extensions) 
    - name: Compile sources windows
      if: contains( matrix.os, 'windows')
      run: |
        make -C src -f makefile EXT=.exe
    - name: Compile sources Linux/mac    
      if: false == contains( matrix.os, 'windows')
      run: |
        make -C src -f makefile
        
   # Compile shared library
    - name: Compile libraries windows 
      if: contains( matrix.os, 'windows')
      run: |
        make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.dll
    - name: Compile libraries linux 
      if: contains( matrix.os, 'ubuntu')
      run: |
        make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.so
    - name: Compile libraries mac 
      if: contains( matrix.os, 'macOS')
      run: |
        make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.dylib
        
   # Test julia  
    - name: Setup julia testing framework
      uses: julia-actions/julia-buildpkg@latest
    - name: Run tests (through julia)
      uses: julia-actions/julia-runtest@latest  
