name: Release Linux binaries

on:
  release:
    types: [created]

jobs:
  generate:

    name: Create release-artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install dependencies linux
        if: contains( matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y gfortran
          
      - name: Compile and tar binaries for linux
        if: contains( matrix.os, 'ubuntu')
        run: |
          make -C src -f makefile
          mkdir binary
          find src/ -executable -type f -exec cp {} binary \;
          tar -pczf Perple_X_Linux_64_gfortran.tar.gz binary datafiles optionfiles matlab_scripts

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.tar.gz'
