name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gfortran
        sudo apt install -y cmake
    - name: Compile sources
      run: |
        make -f makefile
    - name: Compile libraries
      run: |
        make -f makefile clean
        make -f makefile FLINK='-shared' FFLAGS='-fPIC -O3'
