name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install GCC compilers macOS
      if: contains( matrix.os, 'macOS')
      run: |
          brew install gcc@12 
    - name: Compile sources
      run: |
        make -C sources -f makefile
    - name: Compile libraries
      run: |
        make -C sources -f makefile clean
        make -C sources -f makefile FLINK='-shared' FFLAGS='-fPIC -O3'
